[tool.poetry]
name = "minecraft_get_building"
version = "0.1.0"
description = ""
authors = ["konishi0125"]

[tool.poetry.dependencies]
python = "^3.9"
mcpi = "^1.2.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
